#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import git
import sqlite3
from optparse import OptionParser

#optparse stuff
def config():
    """Definition for acceptable options with python's optparse library.
    """
    parser = OptionParser(usage='%prog [options] PATH')
    parser.add_option('-b', '--branch', dest='branch', default='master',
        help="Branch you'd like to parse when checking out REPO.")
    parser.add_option('-t', '--temp', dest='temp', default='tmp/',
        help="Temporary directory you'd like to make a mess in.")

    return parser.parse_args()

def main():
    (opts, args) = config()

    #the repo we've been asked to parse
    #git.Git(opts.temp).clone(args[0])

    # Set up the sqlite3 db
    conn = sqlite3.connect('cores.db')
    c = conn.cursor()
    c.execute('''create table if not exists users
    (username text, count real)''')
    c.execute('''create table if not exists hash
    (hash test, timestampt real)''')
    conn.commit()
    c.close()


if __name__ == '__main__':
    main()

# vim: et:ts=4:sw=4:sts=4

